# This is a basic workflow to help you get started with Actions

name: Deploy github page on success PR

on:
  push:
    branches: [main]
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3

      # install node.js
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "22.11"

      # Runs a single command using the runners shell
      - name: Install dependencies
        run: npm install

      # Runs a single command using the runners shell
      - name: Build the project
        run: npm build

      # Runs a single command using the runners shell
      - name: Try to build the ESLint config preview site
        run: npx @eslint/config-inspector build --base "/eslint-config/"

      # use actions-gh-pages to deploy dist to gh-pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          # github will auto-generate a token for this job and use it
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./.eslint-config-inspector
          publish_branch: config-preview
